---

- name: Check existence of odoo systemd service
  ansible.builtin.stat:
    path: "{{ item.path }}"
  register: odoo_service_stat

- when: odoo_service_stat.stat.exists | bool
  block:
    - name: Ensure odoo service is stopped
      ansible.builtin.service:
        name: "{{ item.service }}"
        state: stopped
        daemon_reload: true
    - name: Ensure odoo service doesn't exist
      ansible.builtin.file:
        dest: "{{ item.path }}"
        state: absent
