---

- name: Ensure odoo services are stopped and removed
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/remove_service.yml"
  with_items:
    - {service: "{{ odoo_identifier }}.service", path: "{{ devture_systemd_docker_base_systemd_path }}/{{ odoo_identifier }}.service"}

- name: Ensure odoo base path is files deleted
  ansible.builtin.file:
    path: "{{ odoo_base_path }}"
    state: absent
