---

- name: Extract database filters from odoo_routers
  ansible.builtin.set_fact:
    odoo_databases: "{{ odoo_routers | map(attribute='dbfilter') | list }}"

- name: Show databases to be upgraded
  ansible.builtin.debug:
    msg: "Will upgrade modules for the following databases: {{ odoo_databases | join(', ') }}"

- name: Stop odoo service
  ansible.builtin.systemd:
    name: "{{ odoo_identifier }}.service"
    state: stopped
  become: true

- name: Upgrade all modules for each database
  ansible.builtin.shell: "{{ odoo_base_path }}/bin/run -d {{ item }} -u all"
  loop: "{{ odoo_databases }}"
  become: true
  register: current_result
  loop_control:
    label: "{{ item }}"

# Display the result of each database immediately after its upgrade
- name: Show upgrade result for current database
  ansible.builtin.debug:
    msg: "Upgrade results for database {{ item.item }}:\n{{ item.stdout_lines | default([]) }}"
  loop: "{{ [current_result] }}"
  when: current_result.stdout_lines is defined

- name: Start odoo service
  ansible.builtin.systemd:
    name: "{{ odoo_identifier }}.service"
    state: started
  become: true
  