---

- name: Fail if required odoo settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - odoo_routers
    - odoo_database_hostname
    - odoo_database_username
    - odoo_database_password
